[package]
name = "hashlife"
version = "0.1.0"
authors = ["AlephAlpha <alephalpha911@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ca-rules = "0.3.2"
rustc-hash = "1.1.0"

[dev-dependencies]
ca-formats = "0.2.1"
criterion = "0.3.3"

[[bench]]
name = "bench"
harness = false

[workspace]
members = ["hashlife-sdl"]
