[package]
name = "hashlife-sdl"
version = "0.1.0"
authors = ["AlephAlpha <alephalpha911@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashlife = { path = "../" }
sdl2 = "0.35.0"
flate2 = "1.0.20"
