[package]
name = "sdl_demo"
version = "0.1.0"
authors = ["AlephAlpha <alephalpha911@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ca-formats = "0.1.3"
hashlife = { path = "../../" }
sdl2 = "0.34.3"
